baseURL = 'https://alexfigar.github.io/'
languageCode = 'en-us'
title = "Alex Figar's Portfolio"
theme = 'PaperMod'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Alex Figars Portfolio"
description = "Alex Figars Portfolio"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Alex Figar"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Alex Figar"
  subtitle = "I am a game developer based in Sydney, Australia. I have 3 years experience working on VR/AR projects in Unity and further 4 years with C#/VB in the legal tech industry."
  imageUrl = "profile.jpg"
  imageWidth = 200
  imageHeight = 200
  imageTitle = "profile image"

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"
    [[params.profileMode.buttons]]
    name = "Categories"
    url = "categories"

  [params.homeInfoParams]
  Title = "Hi there"
  Content = "My name is Alex Figar, I am a game developer based in Sydney, Australia"
  imageUrl = "profile.jpg"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@AlexFigar"
  [[params.socialIcons]]
  name = "BlueSky"
  url = "hhttps://bsky.app/profile/alexfigar.bsky.social"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/AlexFigar"

  [[params.socialIcons]]
  name = "x"
  url = "https://x.com/alex_figar"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

  [params.editPost]
  URL = "https://github.com/AlexFigar/alexfigar.github.io/tree/master/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 5

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[markup.highlight]
noClasses = false

[markup.goldmark]
renderer.unsafe = true
