baseURL = 'https://alexfigar.github.io/'
languageCode = 'en-us'
title = "Alex Figar's Portofilio"
theme = 'dream'

[params]
lightTheme = "emerald"
darkTheme = "forest"
avatar = "profile.jpg"
headerTitle = "Alex Figar's Portfolio"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
